version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # 1.7 is the last version to support Java 8.
      - dependency-name: "com.google.googlejavaformat:google-java-format"
        versions: ">= 1.8"
