dist: bionic
language: java
jdk:
  - openjdk8
install: true
script: '[ "$TRAVIS_REPO_SLUG" == veithen/parent ] && [ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == false ] && goal=deploy || goal=verify ; mvn -B -s .travis-settings.xml $goal'
env:
  global:
    - secure: "S6PiCV/4QiRIa4bpc89HSmrt+Pbnm26mJrSmEGmrnp8dSj8iBjx0HCxZaSuU9rh6m1nXmQl3QJCVqbYMnXZ03kzGYeLmIBRdemyp3sgiygsWDPkJLfKHjE7+s7Vk/4qTQWQ/VK+qQ8hubii1u60IjGZAoKiPzUcLsIicwt41LkzYKIhnLWzWFYB/JC085IyC3XV07iBsVjddmIIg/YY+rWugj8uuWkLbU6fkAFz8fWVIhhf4jsWZM4KICEpJe6WA9Za5N84qWruw4WsrJkp3d6rBejWv6Njzo/mpoZOItM3OBRDsNjDamErdwYBapfR8UmY6/EEeuBkex/EWabr8VeHgARe5PfbF94P4GQEyqwnbjZrd2iZzfdhUofwnxeb3nlnO0R04mx+kRi+c+em2iCDUMzAkzKixgWQcABPclD34qRGePeswyzqReQbUKvoY4QBap7PQFbaM41Ilyn1EPkpHrlrh666ODk2pFpEgL5LaZWmSfcwD9PN3mwVo8IgcE1AFIiIjuLymdO6Lg3Lz1ZUpLPdvePBRl6KvjhBWSbRIdiBE3ebIkJvGBJlHe+Q5y/Fu+/8PB5A0h5TfRdpwo1lXS7fOJAy9srt7vP9WyjGyvbKH7Ai50eKW4jEwIMDWNzpR2xaD3nFXMPe2uJISc/NJ3zeXc3/lt0G7z5xxsXc="
cache:
  directories:
  - $HOME/.m2
